### PR TITLE
fix: Disable update notifications

### LINKED ISSUE #2: Disable update notifications
Updates are not possible to install through the normal firefox mechanism and have to be done through packaging.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #2

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Think there's any value in having default settings centralized in either packaging-firefox or default-settings, or is this one separate from the others intentionally?

**Comment by jacobgkau** [comment]
I'm seeing the new preferences file get installed, but `app.update.auto` still shows as `true` in `about:config`, and `about:preferences` still has a `Firefox Updates` section.

**Comment by jacobgkau** [comment]
Looks like a character is missing:
```
/usr/lib/firefox/defaults/pref/default-prefs.js:5: prefs parse error: expected ';' after ')'
```

**Review by jackpot51 — DISMISSED** [review]

**Comment by jacobgkau** [comment]
The terminal output is no longer showing up, but it still doesn't seem to actually be working. `app.update.auto` is still set to `true` in `about:config` (although `app.update.enabled` is set to `false` now, where it wasn't showing up at all before), and the setting still shows up and appears enabled in `about:preferences` as well.

**Review by jackpot51 — DISMISSED** [review]

**Comment by mmstick** [comment]
That seems to have done it

appupdate

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This is indeed working to change the `about:config` lines now. I'm still seeing the update section on the preferences page:

Screenshot from 2022-04-04 19-15-25

At least it's set to `let you choose to install them` now (it was set to `Automatically install` before), but that still doesn't sound like exactly what we want. This section does not show up in the Firefox settings on 21.10 at all.

Screenshot from 2022-04-04 19-17-38

It sounds like the `let you choose to install them` option might still notify users about updates. I'm attempting to build an older version of Firefox so I can confirm whether this will work to disable the notifications or not.

**Comment by jacobgkau** [comment]
Creating a `/usr/lib/firefox/distribution/policies.json` file with [this contents](https://github.com/mozilla/policy-templates/blob/master/README.md#disableappupdate) removes the options for auto-updating or notifying (without removing the header), but it also causes a `Your browser is being managed by your organization.` message to show up at the top of the Preferences page. (It [looks like](https://blog.linuxmint.com/?p=4259) Linux Mint is doing is this way.)

**Comment by jackpot51** [comment]
99.0 released today, so it should be easy to test it with the change @jacobgkau recommends

**Review by jacobgkau — APPROVED** [review]
This disables auto-updating using the best currently known mechanisms. I am not receiving any notifications about Firefox 99 today, there is no way to check for updates manually from within the browser anymore, and the link in the `About Mozilla Firefox` dialog that @cwsystem76 was concerned about is no longer showing after the last commit.

Screenshot from 2022-04-05 10-36-26

Clicking the `Your browser is being managed by your organization.` link in the preferences page shows that the only policy we're setting is the one to disable updates.

Screenshot from 2022-04-05 10-37-10

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
